name: dsc_event_adder
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in: ^4.2.0
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  image_picker: ^0.6.3+4
  firebase_storage: ^3.1.3
  datetime_picker_formfield: ^1.0.0
  expandable: ^4.1.2
  qrscan: ^0.2.17
  path_provider: ^1.6.5
  csv: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    
  fonts:
     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf